apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-hello-os
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      
      - image: 244740641779.dkr.ecr.us-east-1.amazonaws.com/team2:latest
        name: hello
 
        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "250m"
       
