apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-form
  labels:
    app: form
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form
  template:
    metadata:
      labels:
        app: form
    spec:
      containers: 
      - image: 244740641779.dkr.ecr.us-east-1.amazonaws.com/team2:latest
        name: form
 
        ports:
        - containerPort: 8000

        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "500m"
