apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-hello-os
  namespace: dev
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers: 
      - image: 244740641779.dkr.ecr.us-east-1.amazonaws.com/team2:latest
        name: hello
        imagePullPolicy: Always 
 
        ports:
        - containerPort: 8000

        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "500m"
