name: Github to Jira integration

on:
  push: 
    branches: 
      - 'features/**'

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASEURL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        
    - name: Find Issue Key
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
        string: ${{ github.event.ref }}
        
        
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "IN PROGRESS"
        
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
        issue: ${{ steps.find.outputs.issue }}
        comment: "${{ github.head_ref }} pushed to repository: ${{ github.event.repository.full_name }}"

#   PrRequest: 
#     needs: test-transition-issue
#     name: create_prRequest
#     runs-on: ubuntu-latest
#     steps:
#     - name: Login
#       uses: atlassian/gajira-login@master
#       env:
#         JIRA_BASE_URL: ${{ secrets.JIRA_BASEURL }}
#         JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
#         JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
#     - name: Transition review
#       uses: atlassian/gajira-transition@master
#       with:
#         issue: ${{ github.head_ref }}
#         transition: "ReadyForCodeReview"
