name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.3'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.acessKeyID }}
        aws-secret-access-key: ${{ secrets.scretAccessKey }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Load secrets and save to app.env
      run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: aws_depolyment_team2
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
    - name: Update kube config
      run: >
        SET AWS_ACCESS_KEY_ID=ASIATR65N2PZVL2CRJMT
        SET AWS_SECRET_ACCESS_KEY=GoAXkSFwDViHyx82MmQa/3jFdhXPXRSAXFwtTJ/Z
        SET AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEBcaCXVzLWVhc3QtMSJIMEYCIQDzVXIOvJ3zqB/bmTbhYNG5OQCK8AbjI2N6zy+BpPet9wIhALGh25iWQatNvDnn7ZL3dIjLoaR7NYv6/TnP1CXyv4FxKp4DCHAQABoMMjQ0NzQwNjQxNzc5IgyMx23UfdAlEKJgCCoq+wInAclSw6sSBi6tg9m84n06R5yHCwkTCLJjPUpMmnMt/khyYifEn/BBp2gOUsdNb7z/rPrFIgcFXlglVmjWsbzy28dXS/1t3bfAPHDfsTOamaKnZSMOFJ/Ht7nYsccjP6k1Ve41fQfbXOi8OGVCxm6zPrG2DGIxDm6UBiV1mkqR6D/WuPwgRyOKHG9cxz2UyGl5iBIFbK+meD9jCLrEJzox9frHdPxcywD9Li8BcB3GmHgT0/B7mH+ByY7xci2CoaNCkzIY7Xrl+XzFPhF4wIh9x8Z1AiH7HUjSGHFZ3CdsixjIezxrAydem/JR1Ai5iTSjiQ0CBa7DtYEo9jx+UYYBKQ+6h1tVE+XECXttOCBFgwebjDq2evr8vAAY9itxH3sQcKKx/Z4nP+L8UF37S1jnv5FnDnw9Tfew2Bq4b3bZ4wxu5ZJgbkeMMDqcGmMt6pjBXNO1UwDw2NLvSXq9FPksq2FRvm8SFt3GyEbLu5AV9ITI2muogG56/hIiMMKUo5cGOqUBrV7BQH74l7tvFzBvMQbveVMcPPjLMZFXhoL9bmfzfZHG17TVm28yN5WGmknzXqzNmzIIyRvLUZFRj4maTi2SdwQ6DRuFZxkUYATHJp07TLT7UV9VGK8aG8wkwqL4v27OfxP47Lv3Lh7JLbOAPcnZQxDf67QtgsFsM6xHJpO/blnXVSYpqzzY6dkEoUMnjevUrqJLlxLqC3eV77Hw/YyCWbZUWjyF
    
    - name: jai shree ram
      run: aws eks --region us-east-1 update-kubeconfig --name aws_depolyment_team2

    - name: Deploy image to Amazon EKS
      run: |
        kubectl apply -f eks/aws-auth.yaml
        kubectl apply -f eks/dev.yaml
        kubectl apply -f eks/service.yaml
        kubectl apply -f eks/issuer.yaml
        kubectl apply -f eks/ingress.yaml
