name: pr merge

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.3'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Load secrets and save to app.env
      run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: team2
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
    - name: Update kube config
      run: aws eks --region us-east-1 update-kubeconfig --name aws_depolyment_team2
     

    - name: Deploy image to Amazon EKS
      run: |
        kubectl apply -f deployProd.yaml
        kubectl apply -f serviceProd.yaml
        kubectl rollout restart deployment react-form -n default

  test-transition-issue:
    needs:  deploy
    name: Transition merge
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASEURL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

    - name: Transition merged
      uses: atlassian/gajira-transition@master
      if: github.event.pull_request.merged == true
      with:
        issue: ${{ github.head_ref }}
        transition: "InCodeReview"

  

  QA: 
    needs: test-transition-issue
    name: Transition Issue
    runs-on: ubuntu-latest
    steps: 
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASEURL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
      - name: Transition review
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ github.head_ref }}
          transition: "ReadyForQAReview"

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test -- --coverage

      - name: Transition review
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ github.head_ref }}
          transition: "ReadyForQADeployment"
      
      # - name: Login
      #   uses: atlassian/gajira-login@master
      #   env:
      #     JIRA_BASE_URL: ${{ secrets.JIRA_BASEURL }}
      #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
      - name: Transition review
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ github.head_ref }}
          transition: "ReadyForStagingRelease"

  Sonar: 
    needs: QA
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: sonarsource/sonarqube-scan-action@dev
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASEURL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
      - name: Transition sonar
        uses: atlassian/gajira-transition@master
        if: github.event.pull_request.merged == true
        with:
          issue: ${{ github.head_ref }}
          transition: "ReadyForProdRelease"
