name: Github to Jira integration

on:
  pull_request: 
    branches: 
      - dev

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASEURL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
        
    - name: Find Issue Key
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits
        
        
#     - name: Transition issue
#       uses: atlassian/gajira-transition@master
#       with:
#         issue: ${{ steps.find.outputs.issue }}
#         transition: "IN PROGRESS"
